version: '3'

services:
  Quantum Documents:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    shm_size: '2gb'
    ports:
      - '${Quantum Documents_PORT}:7860'
    volumes:
      - cache:/workspace/.cache
      - save:/workspace/save
    command: ${Quantum Documents_ARGS}
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]

volumes:
  cache:
  save:
